baseURL = "https://dssg-berlin.org/dssg-berlin.org/"
languageCode = "de-de"
title = "DSSG Berlin"
theme = "dssg"

DefaultContentLanguage = "de"

sectionPagesMenu = "main"
RelativeURLs = true
CanonifyURLs = true

[languages]
[languages.en]
languageName = "English"
weight = 2
copyright = "Creative Commons Attribution Share Alike 4.0"

[languages.de]
languageName = "Deutsch"
copyright = "Creative Commons Attribution Share Alike 4.0"
title = "DSSG Berlin"
weight = 1