name: GitHub Pages

on:
    push:
        branches:
        - master-test

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - run: shell ./github/deploy.sh
          env:
              GITHUB_TOKEN: ${{ secrets.github_token }}
