name: Deploy Hugo site to Pages

on:                                              
  push:
    branches:
    - fix-deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1                  
      with:
        submodules: true

    - name: Setup Hugo                           
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.69.2'
        extended: true

    - name: Build                                
      run: hugo

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ./public
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy                               
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
